/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class PenambahanDuaAngka extends javax.swing.JFrame {
    int hasil = 0;
    /**
     * Creates new form PenambahanDuaAngka
     */
    public PenambahanDuaAngka() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TextAngkaPertama = new javax.swing.JTextField();
        TextAngkaKedua = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TextHasil = new javax.swing.JTextField();
        ButtonPenambahan = new javax.swing.JButton();
        ButtonPengurangan = new javax.swing.JButton();
        ButtonPembagian = new javax.swing.JButton();
        ButtonPerkalian = new javax.swing.JButton();
        ButtonHapus = new javax.swing.JButton();
        ButtonKeluar = new javax.swing.JButton();
        LabelOperator = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Operasi Dua Angka"));

        jLabel1.setText("Masukkan Angka");

        jLabel2.setText("=");

        ButtonPenambahan.setText("Penambahan");
        ButtonPenambahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPenambahanActionPerformed(evt);
            }
        });

        ButtonPengurangan.setText("Pengurangan");
        ButtonPengurangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPenguranganActionPerformed(evt);
            }
        });

        ButtonPembagian.setText("Pembagian");
        ButtonPembagian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPembagianActionPerformed(evt);
            }
        });

        ButtonPerkalian.setText("Perkalian");
        ButtonPerkalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPerkalianActionPerformed(evt);
            }
        });

        ButtonHapus.setText("Hapus");
        ButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHapusActionPerformed(evt);
            }
        });

        ButtonKeluar.setText("Keluar");
        ButtonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKeluarActionPerformed(evt);
            }
        });

        LabelOperator.setText("+");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonPenambahan)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TextAngkaPertama, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelOperator)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextAngkaKedua, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(TextHasil))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonPengurangan)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonPembagian)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonPerkalian)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonHapus)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonKeluar)
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextAngkaPertama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(TextHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextAngkaKedua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelOperator))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonPenambahan)
                    .addComponent(ButtonPengurangan)
                    .addComponent(ButtonPembagian)
                    .addComponent(ButtonPerkalian)
                    .addComponent(ButtonHapus)
                    .addComponent(ButtonKeluar))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonPenambahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPenambahanActionPerformed
        hasil = getAngkaPertama()+getAngkaKedua();
        TextHasil.setText(hasil+"");
        LabelOperator.setText("+");
    }//GEN-LAST:event_ButtonPenambahanActionPerformed

    private void ButtonPenguranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPenguranganActionPerformed
        hasil = getAngkaPertama()-getAngkaKedua();
        TextHasil.setText(hasil+"");
        LabelOperator.setText("-");
    }//GEN-LAST:event_ButtonPenguranganActionPerformed

    private void ButtonPembagianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPembagianActionPerformed
        hasil = getAngkaPertama()/getAngkaKedua();
        TextHasil.setText(hasil+"");
        LabelOperator.setText(":");
    }//GEN-LAST:event_ButtonPembagianActionPerformed

    private void ButtonPerkalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPerkalianActionPerformed
        hasil = getAngkaPertama()*getAngkaKedua();
        TextHasil.setText(hasil+"");
        LabelOperator.setText("X");
    }//GEN-LAST:event_ButtonPerkalianActionPerformed

    private void ButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHapusActionPerformed
        TextAngkaPertama.setText("");
        TextAngkaKedua.setText("");
        TextHasil.setText("");
        LabelOperator.setText("");
        TextAngkaPertama.requestFocus();
    }//GEN-LAST:event_ButtonHapusActionPerformed

    private void ButtonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKeluarActionPerformed
        String tanya = "Apakah Anda Yakin akan Keluar dari Aplikasi?";
        boolean Yakin = JOptionPane.showConfirmDialog(rootPane, tanya)== JOptionPane.YES_OPTION;
        if(Yakin){
            System.exit(0);
        }
    }//GEN-LAST:event_ButtonKeluarActionPerformed
    
    private int getAngkaPertama(){
        return Integer.valueOf(TextAngkaPertama.getText());
    }
    
    private int getAngkaKedua(){
        return Integer.valueOf(TextAngkaKedua.getText());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenambahanDuaAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenambahanDuaAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenambahanDuaAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenambahanDuaAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenambahanDuaAngka().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonHapus;
    private javax.swing.JButton ButtonKeluar;
    private javax.swing.JButton ButtonPembagian;
    private javax.swing.JButton ButtonPenambahan;
    private javax.swing.JButton ButtonPengurangan;
    private javax.swing.JButton ButtonPerkalian;
    private javax.swing.JLabel LabelOperator;
    private javax.swing.JTextField TextAngkaKedua;
    private javax.swing.JTextField TextAngkaPertama;
    private javax.swing.JTextField TextHasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
